{
  config,
  lib,
  pkgs,
  myConfig,
  ...
}:

# Home-manager wiring for Emacs. The *configuration* itself is no longer here —
# it lives in its own repo and arrives as the `emacs-config` flake input.
#
# What stayed: the packages Emacs shells out to, the daemon, recoll.conf, and
# the scaffolding of directories Emacs expects to exist. All of that describes
# what THIS MACHINE provides. What left: init.el, early-init.el, the 40 literate
# modules, and the tools that build them — those describe what the CONFIG is,
# and they run on Windows and macOS too.
#
# The thing that actually went away is the staging hop. This module used to
# install the modules read-only at ~/.config/emacs/modules-src and then run a
# 20-line activation script that was a hand-rolled mtime-gated `cp` into a
# *writable* ~/.config/emacs/modules, because the Nix store is read-only and
# Emacs tangles .el next to .org at runtime.
#
# That copy was a directory Nix did not own: it could not roll it back, could
# not garbage-collect it, and never deleted from it — the sync only ever added.
# The config looked pinned and behaved mutable. Now the modules are tangled at
# BUILD time by the input's own flake, so what lands here is an immutable store
# symlink and the hop has no reason to exist.

let
  # Both come from the emacs-config flake input, threaded via myConfig so this
  # module does not need `inputs` plumbed down to it.
  emacs = myConfig.emacsPackage; # Emacs + the package set the config expects
  inherit (myConfig)
    emacsConfig # that repo, with every module pre-tangled
    seforimPath
    ;
  homeDir = config.home.homeDirectory;

  inherit (config.shaulos.palette) font;

  # ── The one module this machine adds to that repo ────────────────────────
  #
  # Emacs is allowed to name its own size — it is a text editor, that is a
  # reasonable thing for it to have an opinion about, and `01-ui.el` in the
  # emacs-config repo does exactly that. What it cannot do is know what the
  # rest of *this* display is set to. So the mechanism stays and the number
  # comes from here, which is `uiSize` in ../../system/appearance.nix.
  #
  # ── Three separate bugs this fixes, all of them measured ─────────────────
  #
  # 1. **The font was not the one this machine themes with.** `01-ui.el` picks
  #    the first installed family from a portable list that starts
  #    `"JetBrains Mono"` — with a space, which is the upstream name. This
  #    machine installs the Nerd Font patch, and `fc-list : family` calls that
  #    `JetBrainsMono Nerd Font`, no space. The two do not match, so the search
  #    fell through to the fourth entry and Emacs has been rendering in
  #    **DejaVu Sans Mono** while every other surface used JetBrainsMono.
  #    Measured, not guessed: `(face-attribute 'default :family)` in a frame
  #    running the real config answers `DejaVu Sans Mono`.
  #
  # 2. **The daemon never ran that code at all.** The whole font block is
  #    wrapped in `(when (display-graphic-p) …)` evaluated at *load* time. In
  #    `emacs --fg-daemon` — which is what services.emacs runs, and what
  #    `EDITOR=emacsclient` therefore talks to — there is no frame yet at load
  #    time, so `display-graphic-p` is nil and the block is skipped outright.
  #    Every frame `emacsclient -c` has ever made got no `:height` from the
  #    config: it fell through to whatever fontconfig's default was, which
  #    until this week was 12.0pt. That is the "Emacs is huge" report, exactly,
  #    and it is why a standalone `emacs` looked different from a client frame.
  #    Hooking `after-make-frame-functions` is the fix, and it is the half
  #    `(when (display-graphic-p))` can never do on its own.
  #
  # 3. The size itself was a literal, 90, in a repo that knows nothing about
  #    this panel.
  #
  # Numbered 99 so it loads after 01-ui.el — init.el loads each module
  # directory in lexical order, and last writer wins on a face attribute.
  fontModule = pkgs.writeText "99-local-fonts.el" ''
    ;;; 99-local-fonts.el --- machine-local font size -*- lexical-binding: t; -*-
    ;;; Commentary:
    ;; Generated by modules/home/emacs/default.nix in the nixos-config repo.
    ;; Do not edit: it is a store path. The size is `uiSize' in
    ;; modules/system/appearance.nix and nothing else decides it.
    ;;; Code:

    (defconst shaulos/mono "${font.mono}"
      "The monospace family stylix themes this machine with.")

    (defconst shaulos/height ${toString (font.sizes.applications * 10)}
      "Default face height, in tenths of a point.")

    (defun shaulos/apply-font (&optional frame)
      "Set FRAME's default face from the values this machine derived."
      (when (display-graphic-p frame)
        (set-face-attribute 'default frame
                            :family shaulos/mono
                            :height shaulos/height
                            :weight 'regular)))

    ;; Both halves are needed. The call covers a frame that already exists —
    ;; a standalone `emacs'. The hook covers every frame made later, which in
    ;; a daemon session is all of them.
    (shaulos/apply-font)
    (add-hook 'after-make-frame-functions #'shaulos/apply-font)

    (provide '99-local-fonts)
    ;;; 99-local-fonts.el ends here
  '';

  # The emacs-config modules tree with that one file added. It has to be a
  # rebuilt directory rather than a second `home.file` entry, because
  # ~/.config/emacs/modules is itself a store symlink — you cannot drop a file
  # into it, only into a copy of it.
  emacsModules = pkgs.runCommand "emacs-modules-local" { } ''
    cp -r ${emacsConfig}/modules $out
    chmod -R u+w $out
    cp ${fontModule} $out/essentials/99-local-fonts.el
  '';
in
{
  # For `config.shaulos.palette`, which is where the font family and the sizes
  # come from. Importing it twice is free — home-manager dedupes by path.
  imports = [ ../palette.nix ];

  # The test for belonging in this list: would you still want it if you
  # uninstalled Emacs? If yes it is a tool and it lives in ../toolkit.nix.
  # `recoll`, `plocate`, `fd`, `ripgrep`, `ripgrep-all` and `pandoc` were listed
  # here *and* in modules/system/cli-tools.nix, and they all pass that test —
  # so toolkit.nix owns them now, and the seforim search, Org export and the
  # Markdown preview keep working because it installs them in every session
  # including study. What is left is what exists only because Emacs shells out
  # to it.
  home.packages = [
    emacs
  ]
  ++ (with pkgs; [
    texlive.combined.scheme-full
    typst
    tinymist
    sqlite
    graphviz
    imagemagick
    tree-sitter
    hdate
    jdt-language-server
    nil
    rust-analyzer
    pyright
    lua-language-server
  ]);

  # ── Which halves of the config load here ────────────────────────────────
  # The emacs-config repo ships two module groups: `essentials/`, which is a
  # general Emacs configuration that knows nothing about Hebrew or seforim, and
  # `extras/`, the personal half that layers on top of it. Its `init.el`
  # defaults to both and reads `EMACS_MODULE_GROUPS' to be told otherwise, so
  # naming the groups is this machine's call to make and not the repo's.
  #
  # Set in BOTH places on purpose, and they are not redundant:
  #
  #   home.sessionVariables         -> ~/.profile etc., i.e. anything launched
  #                                    from a shell, including a bare `emacs'.
  #   systemd.user.sessionVariables -> environment.d, which is the only one of
  #                                    the two that `emacs.service' ever reads.
  #
  # The daemon is not started from a shell, so the first line alone would leave
  # every `emacsclient' frame — which is what EDITOR resolves to, three lines
  # down — loading a different set of modules than a standalone Emacs. That is
  # the kind of split that costs an afternoon to notice.
  #
  # To swap for one session rather than for the machine, leave this alone and
  # override it in the environment:
  #
  #   EMACS_MODULE_GROUPS="essentials extras" emacs
  #   systemctl --user set-environment EMACS_MODULE_GROUPS="essentials extras"
  #   systemctl --user restart emacs.service
  home.sessionVariables = {
    EDITOR = "emacsclient -c -a ''";
    VISUAL = "emacsclient -c -a ''";
    EMACS_MODULE_GROUPS = "essentials";
  };

  systemd.user.sessionVariables.EMACS_MODULE_GROUPS = "essentials";

  services.emacs = {
    enable = true;
    package = emacs;
    client = {
      enable = true;
      # Each list element is a distinct argv token; "-a ''" as one token would
      # be passed to emacsclient literally and mis-parsed. Split them.
      arguments = [
        "-c"
        "-a"
        ""
      ];
    };
  };

  # ── The config, pinned ──────────────────────────────────────────────────
  # `${emacsConfig}` is the emacs-config repo after its flake ran tangle.sh, so
  # modules/ holds both the .org sources and the generated .el. Nothing tangles
  # at startup: init.el skips any module directory that is not writable, and
  # this one is a store path.
  #
  # ~/.config/emacs itself stays a real, writable directory — Emacs writes
  # custom.el, eln-cache, transient state and the org-roam db in there. Only
  # the three config entries are store symlinks.
  home.file.".config/emacs/init.el".source = "${emacsConfig}/init.el";
  home.file.".config/emacs/early-init.el".source = "${emacsConfig}/early-init.el";
  # Not `${emacsConfig}/modules` directly — see `emacsModules` above. The tree
  # is that one plus a 99- module carrying the font size this display wants.
  home.file.".config/emacs/modules".source = emacsModules;

  # `noaspell` was indented four columns further than every line around it.
  # recoll.conf is read by recoll's ConfSimple parser, in which indentation is
  # not decoration — it is how the format spells a continuation of the previous
  # line's value. Left as it was, `followLinks` was at best being handed a value
  # it does not take, and `noaspell` at worst was not a setting at all.
  home.file.".recoll/recoll.conf".text = ''
    topdirs = ${seforimPath}
    followLinks = 1
    noaspell = 1
    indexedmimetypes = text/x-org text/org text/plain text/markdown application/pdf
    unac_except_stripping = true
    snippetMaxPosWalk = 1000000
    maxTermExpand = 10000
  '';

  # ── One-time migration off the writable modules directory ───────────────
  # Before this change ~/.config/emacs/modules was a real directory that Nix
  # wrote into. It is now a symlink into the store, and home-manager's
  # `checkLinkTargets` refuses to replace an existing real directory — so move
  # it aside first, before the link step runs.
  #
  # MOVED, not deleted, and deliberately: the whole problem with the old scheme
  # was that a hand-edit in there could silently have become the live config
  # while the repo went stale. If that happened, those edits are the only copy.
  # Diff modules.pre-flake-input against the emacs-config repo before you throw
  # it away.
  home.activation.migrateEmacsModules = lib.hm.dag.entryBefore [ "checkLinkTargets" ] ''
    emacsDir="${homeDir}/.config/emacs"
    if [ -e "$emacsDir/modules" ] && [ ! -L "$emacsDir/modules" ]; then
      echo "emacs: ~/.config/emacs/modules is now a store symlink."
      echo "emacs: moving the old writable copy to modules.pre-flake-input —"
      echo "emacs: diff it against the emacs-config repo before deleting it."
      $DRY_RUN_CMD rm -rf "$emacsDir/modules.pre-flake-input"
      $DRY_RUN_CMD mv "$emacsDir/modules" "$emacsDir/modules.pre-flake-input"
    fi
    # modules-src was the read-only staging half of the same hack.
    if [ -e "$emacsDir/modules-src" ] && [ ! -L "$emacsDir/modules-src" ]; then
      $DRY_RUN_CMD rm -rf "$emacsDir/modules-src"
    fi
  '';

  home.activation.createOrgSetup = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    mkdir -p "${homeDir}/.cache/emacs/undo-tree-history"
    mkdir -p "${homeDir}/.cache/emacs/seforim"
    mkdir -p "${homeDir}/Documents/org"
    mkdir -p "${homeDir}/Documents/roam/daily"
    mkdir -p "${seforimPath}/Bavli"

    [ ! -f "${homeDir}/Documents/org/inbox.org" ] && echo -e "* Tasks\n* Notes" > "${homeDir}/Documents/org/inbox.org"
    [ ! -f "${homeDir}/Documents/org/journal.org" ] && echo "#+TITLE: Journal" > "${homeDir}/Documents/org/journal.org"
    [ ! -f "${homeDir}/Documents/org/research.org" ] && echo "#+TITLE: Research" > "${homeDir}/Documents/org/research.org"
    [ ! -f "${homeDir}/Documents/bibliography.bib" ] && echo "% Bibliography" > "${homeDir}/Documents/bibliography.bib"
    [ ! -f "${homeDir}/.cache/emacs/seforim/study-log.el" ] && echo "nil" > "${homeDir}/.cache/emacs/seforim/study-log.el"
    true
  '';
}
