{
  config,
  lib,
  pkgs,
  myConfig,
  ...
}:

# Home-manager wiring for Emacs. The *configuration* itself is no longer here —
# it lives in its own repo and arrives as the `emacs-config` flake input.
#
# What stayed: the packages Emacs shells out to, the daemon, the scaffolding of
# directories Emacs expects to exist, the generated `99-local-fonts.el` that
# carries this display's font size into the config, and the choice of which
# module groups load. All of that describes what THIS MACHINE provides. What
# left: init.el, early-init.el, the 40 literate modules, and the tools that
# build them — those describe what the CONFIG is, and they run on Windows and
# macOS too.
#
# (recoll.conf used to be in that first list. It is switched off with `extras`
# now — see the EMACS_MODULE_GROUPS section below, which is also where the
# "which module groups load" half is argued.)
#
# The thing that actually went away is the staging hop. This module used to
# install the modules read-only at ~/.config/emacs/modules-src and then run a
# 20-line activation script that was a hand-rolled mtime-gated `cp` into a
# *writable* ~/.config/emacs/modules, because the Nix store is read-only and
# Emacs tangles .el next to .org at runtime.
#
# That copy was a directory Nix did not own: it could not roll it back, could
# not garbage-collect it, and never deleted from it — the sync only ever added.
# The config looked pinned and behaved mutable. Now the modules are tangled at
# BUILD time by the input's own flake, so what lands here is an immutable store
# symlink and the hop has no reason to exist.

let
  # Both come from the emacs-config flake input, threaded via myConfig so this
  # module does not need `inputs` plumbed down to it.
  emacs = myConfig.emacsPackage; # Emacs + the package set the config expects
  inherit (myConfig)
    emacsConfig # that repo, with every module pre-tangled
    ;
  # `seforimPath` used to be inherited here too, for recoll.conf and the
  # ~/Documents/seforim/Bavli scaffold. Both are switched off below with
  # EMACS_MODULE_GROUPS — see that section — so the binding would be dead, and
  # `deadnix --fail` in flake.nix's checks is right to say so.
  # modules/system/data.nix still reads it from myConfig, which is why it stays
  # declared in flake.nix.
  homeDir = config.home.homeDirectory;

  inherit (config.shaulos.palette) font;

  # ── The one module this machine adds to that repo ────────────────────────
  #
  # Emacs is allowed to name its own size — it is a text editor, that is a
  # reasonable thing for it to have an opinion about, and `01-ui.el` in the
  # emacs-config repo does exactly that. What it cannot do is know what the
  # rest of *this* display is set to. So the mechanism stays and the number
  # comes from here, which is `uiSize` in ../../system/appearance.nix.
  #
  # ── Three separate bugs this fixes, all of them measured ─────────────────
  #
  # 1. **The font was not the one this machine themes with.** `01-ui.el` picks
  #    the first installed family from a portable list that starts
  #    `"JetBrains Mono"` — with a space, which is the upstream name. This
  #    machine installs the Nerd Font patch, and `fc-list : family` calls that
  #    `JetBrainsMono Nerd Font`, no space. The two do not match, so the search
  #    fell through to the fourth entry and Emacs has been rendering in
  #    **DejaVu Sans Mono** while every other surface used JetBrainsMono.
  #    Measured, not guessed: `(face-attribute 'default :family)` in a frame
  #    running the real config answers `DejaVu Sans Mono`.
  #
  # 2. **The daemon never ran that code at all.** The whole font block is
  #    wrapped in `(when (display-graphic-p) …)` evaluated at *load* time. In
  #    `emacs --fg-daemon` — which is what services.emacs runs, and what
  #    `EDITOR=emacsclient` therefore talks to — there is no frame yet at load
  #    time, so `display-graphic-p` is nil and the block is skipped outright.
  #    Every frame `emacsclient -c` has ever made got no `:height` from the
  #    config: it fell through to whatever fontconfig's default was, which
  #    until this week was 12.0pt. That is the "Emacs is huge" report, exactly,
  #    and it is why a standalone `emacs` looked different from a client frame.
  #    Hooking `after-make-frame-functions` is the fix, and it is the half
  #    `(when (display-graphic-p))` can never do on its own.
  #
  # 3. The size itself was a literal, 90, in a repo that knows nothing about
  #    this panel.
  #
  # Numbered 99 so it loads after 01-ui.el — init.el loads each module
  # directory in lexical order, and last writer wins on a face attribute.
  fontModule = pkgs.writeText "99-local-fonts.el" ''
    ;;; 99-local-fonts.el --- machine-local font size -*- lexical-binding: t; -*-
    ;;; Commentary:
    ;; Generated by modules/home/emacs/default.nix in the nixos-config repo.
    ;; Do not edit: it is a store path. The size is `uiSize' in
    ;; modules/system/appearance.nix and nothing else decides it.
    ;;; Code:

    (defconst shaulos/mono "${font.mono}"
      "The monospace family stylix themes this machine with.")

    (defconst shaulos/height ${toString (font.sizes.applications * 10)}
      "Default face height, in tenths of a point.")

    (defun shaulos/apply-font (&optional frame)
      "Set FRAME's default face from the values this machine derived."
      (when (display-graphic-p frame)
        (set-face-attribute 'default frame
                            :family shaulos/mono
                            :height shaulos/height
                            :weight 'regular)))

    ;; Both halves are needed. The call covers a frame that already exists —
    ;; a standalone `emacs'. The hook covers every frame made later, which in
    ;; a daemon session is all of them.
    (shaulos/apply-font)
    (add-hook 'after-make-frame-functions #'shaulos/apply-font)

    (provide '99-local-fonts)
    ;;; 99-local-fonts.el ends here
  '';

  # The emacs-config modules tree with that one file added. It has to be a
  # rebuilt directory rather than a second `home.file` entry, because
  # ~/.config/emacs/modules is itself a store symlink — you cannot drop a file
  # into it, only into a copy of it.
  emacsModules = pkgs.runCommand "emacs-modules-local" { } ''
    cp -r ${emacsConfig}/modules $out
    chmod -R u+w $out
    cp ${fontModule} $out/essentials/99-local-fonts.el
  '';
in
{
  # For `config.shaulos.palette`, which is where the font family and the sizes
  # come from. Importing it twice is free — home-manager dedupes by path.
  imports = [ ../palette.nix ];

  # The test for belonging in this list: would you still want it if you
  # uninstalled Emacs? If yes it is a tool and it lives in ../toolkit.nix.
  # `recoll`, `plocate`, `fd`, `ripgrep`, `ripgrep-all` and `pandoc` were listed
  # here *and* in modules/system/cli-tools.nix, and they all pass that test —
  # so toolkit.nix owns them now, and the file search, Org export and the
  # Markdown preview keep working because it installs them in every session
  # including study. (`recoll` is the one of those that toolkit.nix now has
  # commented out; it is a seforim tool and seforim is `extras`. Everything
  # else in that sentence is unchanged.) What is left below is what exists only
  # because Emacs shells out to it.
  home.packages = [
    emacs
  ]
  ++ (with pkgs; [
    texlive.combined.scheme-full
    typst
    tinymist
    sqlite
    graphviz
    imagemagick
    tree-sitter
    # `hdate` is off with `extras`. Its only caller in the whole config is
    # extras/04-hebrew-scholarship.org, which guards on
    # `(executable-find "hdate")` and prints "hdate not installed" otherwise —
    # so with `essentials` alone nothing ever asks for it. essentials/00-core
    # names it in a comment listing what the config can shell out to; that is
    # documentation, not a call site.
    # hdate
    jdt-language-server
    nil
    rust-analyzer
    pyright
    lua-language-server
  ]);

  # ── Which halves of the config load here ────────────────────────────────
  # The emacs-config repo ships two module groups: `essentials/`, which is a
  # general Emacs configuration that knows nothing about Hebrew or seforim, and
  # `extras/`, the personal half that layers on top of it. Its `init.el`
  # defaults to both and reads `EMACS_MODULE_GROUPS' to be told otherwise, so
  # naming the groups is this machine's call to make and not the repo's.
  #
  # ── What naming only `essentials` costs, measured ───────────────────────
  #
  # This is the half that was missing when the variable was first set. The
  # mechanism below was verified impeccably; the bill was never itemised, and
  # for one commit this machine was fully provisioned for a feature it could
  # not run.
  #
  #     group        modules   lines   loaded
  #     essentials        25   2,379   yes
  #     extras            15   3,165   no
  #
  # `extras/` is 57% of the configuration. It holds all 89 `seforim-*'
  # functions — 31 of them interactive commands — across `10-'…`16-seforim-*',
  # and the entire Hebrew and RTL layer: `00-hebrew', `01-hebrew-completion',
  # `02-hebrew-org', `03-hebrew-typesetting', `04-hebrew-scholarship',
  # `06-torah-search'. All of it is still copied into the Nix store and
  # symlinked into ~/.config/emacs/modules. None of it is loaded.
  #
  # ── And the rule that follows from it, applied here and everywhere ──────
  #
  # A machine provisioned for code it does not load is a machine whose
  # comments are lying. So every piece of machinery in this repo that existed
  # only to serve `extras/' is switched off in the same breath, commented out
  # rather than deleted with the reason written beside it, so that flipping
  # the line below back to "essentials extras" is a matter of uncommenting the
  # blocks it names. They are:
  #
  #   here              `hdate', ~/.recoll/recoll.conf, and the
  #                     ~/.cache/emacs/seforim + ~/Documents/seforim/Bavli
  #                     scaffolding
  #   ../toolkit.nix    `recoll' and `xapian'
  #   ../../home/focus.nix        the same two, and its stated purpose
  #   ../../modules/system/services.nix   the four-hourly `recollindex' timer
  #
  # ── One thing found while switching them off, worth its own paragraph ───
  #
  # ~/.recoll/recoll.conf below was never read by the seforim search, in any
  # configuration, extras loaded or not. `extras/15-seforim-dream.org' builds
  # its index in a *private* confdir — ~/.cache/emacs/seforim/recoll — and
  # writes its own recoll.conf there, deliberately, so that it "never touches
  # a system-wide recoll setup". `seforim-recoll-index' runs
  # `recollindex -c <that dir>' and `seforim-recoll-search' queries the same.
  #
  # So the system timer and this file's recoll.conf were maintaining a second
  # index, over the same corpus, that nothing has ever queried. That is a
  # stronger reason to switch them off than the module groups are, and it
  # would still hold on the day `extras' comes back.
  #
  # Set in BOTH places on purpose, and they are not redundant:
  #
  #   home.sessionVariables         -> ~/.profile etc., i.e. anything launched
  #                                    from a shell, including a bare `emacs'.
  #   systemd.user.sessionVariables -> environment.d, which is the only one of
  #                                    the two that `emacs.service' ever reads.
  #
  # The daemon is not started from a shell, so the first line alone would leave
  # every `emacsclient' frame — which is what EDITOR resolves to, three lines
  # down — loading a different set of modules than a standalone Emacs. That is
  # the kind of split that costs an afternoon to notice.
  #
  # To swap for one session rather than for the machine, leave this alone and
  # override it in the environment:
  #
  #   EMACS_MODULE_GROUPS="essentials extras" emacs
  #   systemctl --user set-environment EMACS_MODULE_GROUPS="essentials extras"
  #   systemctl --user restart emacs.service
  home.sessionVariables = {
    EDITOR = "emacsclient -c -a ''";
    VISUAL = "emacsclient -c -a ''";
    EMACS_MODULE_GROUPS = "essentials";
  };

  systemd.user.sessionVariables.EMACS_MODULE_GROUPS = "essentials";

  services.emacs = {
    enable = true;
    package = emacs;
    client = {
      enable = true;
      # Each list element is a distinct argv token; "-a ''" as one token would
      # be passed to emacsclient literally and mis-parsed. Split them.
      arguments = [
        "-c"
        "-a"
        ""
      ];
    };
  };

  # ── The config, pinned ──────────────────────────────────────────────────
  # `${emacsConfig}` is the emacs-config repo after its flake ran tangle.sh, so
  # modules/ holds both the .org sources and the generated .el. Nothing tangles
  # at startup: init.el skips any module directory that is not writable, and
  # this one is a store path.
  #
  # ~/.config/emacs itself stays a real, writable directory — Emacs writes
  # custom.el, eln-cache, transient state and the org-roam db in there. Only
  # the three config entries are store symlinks.
  home.file.".config/emacs/init.el".source = "${emacsConfig}/init.el";
  home.file.".config/emacs/early-init.el".source = "${emacsConfig}/early-init.el";
  # Not `${emacsConfig}/modules` directly — see `emacsModules` above. The tree
  # is that one plus a 99- module carrying the font size this display wants.
  home.file.".config/emacs/modules".source = emacsModules;

  # ── The system-wide recoll config, off with `extras` ────────────────────
  #
  # Two reasons, and the second one is the one that matters:
  #
  # 1. Nothing loaded reads it. recoll is a seforim tool, and every `recoll'
  #    call site in the config lives in `extras/'.
  # 2. Nothing ever read it. See the EMACS_MODULE_GROUPS section above:
  #    extras/15-seforim-dream.org builds and queries its index in
  #    ~/.cache/emacs/seforim/recoll with a recoll.conf it writes itself,
  #    explicitly to avoid a system-wide setup. This file's `topdirs' has
  #    therefore only ever fed ../../modules/system/services.nix's timer,
  #    which fed nobody.
  #
  # Kept rather than deleted because the indentation note below is a fact
  # about the format that cost real time to learn, and because turning
  # `extras' back on should be an uncomment, not an archaeology exercise.
  #
  # `noaspell` was indented four columns further than every line around it.
  # recoll.conf is read by recoll's ConfSimple parser, in which indentation is
  # not decoration — it is how the format spells a continuation of the previous
  # line's value. Left as it was, `followLinks` was at best being handed a value
  # it does not take, and `noaspell` at worst was not a setting at all.
  #
  # home.file.".recoll/recoll.conf".text = ''
  #   topdirs = ${seforimPath}   (myConfig.seforimPath — re-add the inherit)
  #   followLinks = 1
  #   noaspell = 1
  #   indexedmimetypes = text/x-org text/org text/plain text/markdown application/pdf
  #   unac_except_stripping = true
  #   snippetMaxPosWalk = 1000000
  #   maxTermExpand = 10000
  # '';

  # ── One-time migration off the writable modules directory ───────────────
  # Before this change ~/.config/emacs/modules was a real directory that Nix
  # wrote into. It is now a symlink into the store, and home-manager's
  # `checkLinkTargets` refuses to replace an existing real directory — so move
  # it aside first, before the link step runs.
  #
  # MOVED, not deleted, and deliberately: the whole problem with the old scheme
  # was that a hand-edit in there could silently have become the live config
  # while the repo went stale. If that happened, those edits are the only copy.
  # Diff modules.pre-flake-input against the emacs-config repo before you throw
  # it away.
  home.activation.migrateEmacsModules = lib.hm.dag.entryBefore [ "checkLinkTargets" ] ''
    emacsDir="${homeDir}/.config/emacs"
    if [ -e "$emacsDir/modules" ] && [ ! -L "$emacsDir/modules" ]; then
      echo "emacs: ~/.config/emacs/modules is now a store symlink."
      echo "emacs: moving the old writable copy to modules.pre-flake-input —"
      echo "emacs: diff it against the emacs-config repo before deleting it."
      $DRY_RUN_CMD rm -rf "$emacsDir/modules.pre-flake-input"
      $DRY_RUN_CMD mv "$emacsDir/modules" "$emacsDir/modules.pre-flake-input"
    fi
    # modules-src was the read-only staging half of the same hack.
    if [ -e "$emacsDir/modules-src" ] && [ ! -L "$emacsDir/modules-src" ]; then
      $DRY_RUN_CMD rm -rf "$emacsDir/modules-src"
    fi
  '';

  # The directories the loaded config expects to exist. The three seforim ones
  # are commented out with `extras' — ~/.cache/emacs/seforim is
  # `seforim--state-dir', which only extras/15-seforim-dream.org and its
  # neighbours ever write to, and study-log.el is that module's own state file.
  #
  # `mkdir -p "${seforimPath}/Bavli"` is the one worth reading the removal of
  # twice. ../../modules/system/data.nix's header is an essay about it: that
  # line ran on every activation, including the first, so the bootstrap's old
  # `[ ! -d "$dst" ]` test was always false and the seforim library never once
  # downloaded. data.nix fixed its half by asking about *files* instead. This
  # removes the other half — the empty directory that made the lie possible —
  # so the two are now belt and braces rather than one fix and one landmine.
  home.activation.createOrgSetup = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    mkdir -p "${homeDir}/.cache/emacs/undo-tree-history"
    # mkdir -p "${homeDir}/.cache/emacs/seforim"
    mkdir -p "${homeDir}/Documents/org"
    mkdir -p "${homeDir}/Documents/roam/daily"
    # mkdir -p "$SEFORIM_PATH/Bavli"   (myConfig.seforimPath — re-add the inherit)

    [ ! -f "${homeDir}/Documents/org/inbox.org" ] && echo -e "* Tasks\n* Notes" > "${homeDir}/Documents/org/inbox.org"
    [ ! -f "${homeDir}/Documents/org/journal.org" ] && echo "#+TITLE: Journal" > "${homeDir}/Documents/org/journal.org"
    [ ! -f "${homeDir}/Documents/org/research.org" ] && echo "#+TITLE: Research" > "${homeDir}/Documents/org/research.org"
    [ ! -f "${homeDir}/Documents/bibliography.bib" ] && echo "% Bibliography" > "${homeDir}/Documents/bibliography.bib"
    # [ ! -f "${homeDir}/.cache/emacs/seforim/study-log.el" ] && echo "nil" > "${homeDir}/.cache/emacs/seforim/study-log.el"
    true
  '';
}
