# modules/home/darktable.nix
# darktable 5.6 (via unstable overlay) + declarative LUTs / styles / lua
#
# Verified sources (git ls-remote + fetch hash checked 2026-09-22):
#   darktable-org/lua-scripts @ 055ef31  sha256-Sd5+ik+Ux4s+5pTYmduhbB9+u4cLakAb2EqL1IThk4k=
#   t3mujinpack/t3mujinpack @ 0b421f3    sha256-2e0gxQD4fhfw5b7lzyoOo5T4GJotGD7S7o4vudVtLC8=  (58M haldcluts)
#   cedeber/hald-clut @ 3b3180f          sha256-R8vyYmcsfk49QsSV3v0QblXcO6U0oIfDyxbHPLwSMdo=  (740M full HaldCLUT, opt-in)
#   rabauke/darktable-styles @ bebfec2   sha256-hMOw9bequAlKnrC0KTGFntfv/d+4rq1/ehpI/adIhfs=
#   shetyeshail/dt.styles @ 1b413fa      sha256-yCON8Bn94pa/qFnXgWWahQLv1DB8HBlZdBdy1jwj1wM=
#   Popul-AR/gmic-luts @ a2ef4c9         sha256-UH0ssqB7CBDbAFqNzgRJPMoSOZMhvMLp884yP5QZIBQ= (tiny, neutral + previews)
# (t3mujinpack is re-declared in raw-editor-sources.nix — same fetch, same
#  store path; darktable reads it from config.shaulos.rawEditors.t3mujinpack.)
#
# Why these:
# - You shoot Nikon NEF (DSC_2655.NEF.xmp seen) — film emulation + B&W styles
#   are the most-used darktable extras. t3mujinpack + rabauke cover Agfa/Ilford/
#   Kodak/Portra/Tri-X/Velvia/etc without 740M cedeber/hald-clut bloat.
# - lua-scripts are bundled since 5.6 but the repo is still the update source;
#   enabling a curated luarc gives GIMP, HDRMerge, enfuse, geotagging, etc.
#
# Layout (all XDG, survives GC):
#   ~/.config/darktable/lua -> lua-scripts
#   ~/.config/darktable/luarc -> generated
#   ~/.config/darktable/styles/{rabauke,shetyeshail}
#   ~/.config/darktable/color/in/NIKON D7200.icc -> built from the same DCP
#       that ART and RawTherapee read directly (raw-editor-sources.nix)
#   ~/Pictures/LUTs -> t3mujinpack HaldCLUT PNGs (lut3d module browses there)
#   ~/.config/darktable/luts -> symlink to ~/Pictures/LUTs for convenience
#
# Add your own: drop .cube/.png into ~/Pictures/LUTs or extend xdg.configFile
# below. Styles: drop *.dtstyle into ~/.config/darktable/styles.
{
  pkgs,
  lib,
  config,
  ...
}:
let
  t3mujinpack = config.shaulos.rawEditors.t3mujinpack;
  luaScripts = pkgs.fetchFromGitHub {
    owner = "darktable-org";
    repo = "lua-scripts";
    rev = "055ef31b09a4a67671aa51c4b2a5a5ea9d1317c7";
    hash = "sha256-Sd5+ik+Ux4s+5pTYmduhbB9+u4cLakAb2EqL1IThk4k=";
  };
  haldClut = pkgs.fetchFromGitHub {
    owner = "cedeber";
    repo = "hald-clut";
    rev = "3b3180f82d4dcea1e6e8c5648473539a910d7f49";
    hash = "sha256-R8vyYmcsfk49QsSV3v0QblXcO6U0oIfDyxbHPLwSMdo=";
  };
  rabaukeStyles = pkgs.fetchFromGitHub {
    owner = "rabauke";
    repo = "darktable-styles";
    rev = "bebfec2a528a6ed0ab34086ff0add24f9f905e2d";
    hash = "sha256-hMOw9bequAlKnrC0KTGFntfv/d+4rq1/ehpI/adIhfs=";
  };
  shetyeStyles = pkgs.fetchFromGitHub {
    owner = "shetyeshail";
    repo = "dt.styles";
    rev = "1b413fa2d86295c241cb1050d1b93b6372dce14c";
    hash = "sha256-yCON8Bn94pa/qFnXgWWahQLv1DB8HBlZdBdy1jwj1wM=";
  };
in
{
  # darktable itself comes from toolkit.nix (pkgs.darktable) which the overlay
  # now points at unstable 5.6.0. No duplicate package here.

  # ── Lua ───────────────────────────────────────────────────────────────
  # darktable 5.6 bundles lua-scripts but reads ~/.config/darktable/lua
  # if present; we point it at the pinned store path.
  xdg.configFile."darktable/lua".source = luaScripts;

  # luarc: which scripts to load. Edit this list; see
  # https://github.com/darktable-org/lua-scripts/blob/master/README.md
  # Use the script_manager to toggle at runtime, or add `require "..."`
  # lines here declaratively.
  xdg.configFile."darktable/luarc".text = ''
    -- generated by modules/home/darktable.nix — edit there, not here
    require "contrib/gimp"
    require "contrib/hdr_merge"
    require "contrib/enfuseAdvanced"
    require "contrib/geoToolbox"
    require "contrib/autostyle"
    require "contrib/copy_attach_detach_tags"
    require "contrib/collectHelper"
    -- uncomment more from lua-scripts/contrib/ as needed:
    -- require "contrib/HDRMerge"
    -- require "contrib/LabelsToTags"
    -- require "contrib/cr2hdr"
    -- require "contrib/fujifilm_dynamic_range"
    -- require "contrib/fujifilm_ratings"
    -- require "contrib/clear_GPS"
  '';

  # ── Camera color (input ICC) ──────────────────────────────────────────
  # darktable reads ~/.config/darktable/color/in/*.icc as input profiles. The
  # D7200 ICC is converted at build time from the very DCP that ART and
  # RawTherapee read directly (raw-editor-sources.nix), so the three editors
  # share one camera calibration state for the NEF files you shoot.
  xdg.configFile."darktable/color/in/NIKON D7200.icc".source = config.shaulos.rawEditors.d7200Icc;

  # ── Styles (*.dtstyle) ───────────────────────────────────────────────
  # Both collections are linked read-only into the styles dir.
  # darktable scans ~/.config/darktable/styles on startup.
  xdg.configFile."darktable/styles/rabauke".source = rabaukeStyles;
  xdg.configFile."darktable/styles/shetyeshail".source = shetyeStyles;

  # ── LUTs (HaldCLUT PNGs for the lut3d module) ───────────────────────
  # t3mujinpack holds ~200 film emulations as 512x512 HaldCLUT PNGs (~58M).
  # hald-clut is the full collection (~740M, Apple + Fuji + Film Simulation etc).
  # Both work with darktable's lut3d, RawTherapee, etc.
  # Placed in ~/Pictures/LUTs (browsable) and linked in XDG for parity.
  home.file."Pictures/LUTs/t3mujinpack".source = "${t3mujinpack}/haldcluts";
  xdg.configFile."darktable/luts/t3mujinpack".source = "${t3mujinpack}/haldcluts";
  home.file."Pictures/LUTs/hald-clut".source = "${haldClut}/HaldCLUT";
  xdg.configFile."darktable/luts/hald-clut".source = "${haldClut}/HaldCLUT";

  # Optional: add more LUT packs declaratively as you discover them.
  # Example (uncomment, fill rev/hash via `nix-prefetch`):
  # home.file."Pictures/LUTs/free-luts".source = pkgs.fetchFromGitHub {
  #   owner = "free"; repo = "luts"; rev = "..."; hash = "sha256-...";
  # };

  # Helper to verify darktable sees everything
  home.packages = [
    (pkgs.writeShellScriptBin "darktable-verify" ''
      set -e
      echo "darktable: $(darktable --version | head -n1)"
      echo "lua: $(ls -1 ~/.config/darktable/lua/contrib 2>/dev/null | wc -l) scripts in ~/.config/darktable/lua"
      echo "luarc: $(cat ~/.config/darktable/luarc 2>/dev/null | grep -c '^require')"
      echo "styles: $(find ~/.config/darktable/styles -name '*.dtstyle' 2>/dev/null | wc -l) dtstyles"
      echo "LUTs: $(find ~/Pictures/LUTs -type f \( -name '*.png' -o -name '*.cube' \) 2>/dev/null | wc -l) files in ~/Pictures/LUTs"
      echo "luts XDG: $(ls -1 ~/.config/darktable/luts 2>/dev/null | head)"
    '')
  ];
}
