# modules/home/lisp.nix
#
# Common Lisp. `sbcl` and `quicklisp` are installed by ./toolkit.nix (rule 3:
# things a person types); this file is the wiring that makes the pair usable,
# which is the part that is easy to miss and impossible to guess.
#
# ── The problem this file exists to solve ────────────────────────────────
#
# `sbcl` alone is not a Lisp environment. It compiles Lisp and has no package
# manager, so there is nothing to install a library with — the standard library
# is ANSI CL and stops there. Quicklisp is what fills that in, and its interface
# is two forms:
#
#   (load "…/quicklisp/setup.lisp")
#   (ql:quickload "alexandria")
#
# So a REPL needs the first to have already run, and *that* is the whole job of
# this file. There is no wrapper that saves you from it, and
# packages/quicklisp.nix explains why a wrapped `sbcl` is deliberately not
# provided: CIDER, SLIME and anything that execs `sbcl` by name expect the real
# one.
#
# ── Why the store path cannot be used directly ───────────────────────────
#
# Because Quicklisp writes into its own install directory at runtime. Not
# optionally — this was measured, and the list is not short:
#
#   dists/quicklisp/systems.cdb-tmp    every quickload that resolves a system
#   dists/quicklisp/releases.cdb-tmp   same, on a release query
#   local-projects/system-index.txt    every load (see below)
#   cache/asdf-fasls/…                 the ASDF fasl, compiled on first use
#   dists/quicklisp/software/…         the downloaded libraries themselves
#
# Against /nix/store that is SIMPLE-FILE-ERROR "Error opening … systems.cdb-tmp"
# on the first `ql:quickload`, every time, with no workaround short of not
# using the store path. Local-projects is the subtle one: `local-projects.lisp`
# registers a directory scanner, and `register-local-projects` writes
# system-index.txt unconditionally — so it fails even when you have no local
# projects, which is the common case.
#
# So: the store path is the *source*, and ~/.local/share/quicklisp is the live
# copy. The copy is made once, by the code below, and is only ever written by
# Quicklisp.
#
# ── Why that is still not the stray it looks like ───────────────────────
#
# The instinct is that a directory nobody declared is exactly what the rest of
# this repo exists to prevent, and for a plain `git clone` into $HOME it is. The
# difference is what created it and what it holds: it is seeded from a pinned
# store path rather than fetched ad hoc, it contains only a cache Quicklisp
# regenerates on demand, and it is stated here in the Nix config rather than
# being discovered later. A `home.file` cannot own it — it is written
# continuously — so it is declared as a directory, seeded, and left alone.
#
# The alternative was a writable Quicklisp in the *system* profile so `study`
# could take it away. That was rejected: study removes browsers and fetchers,
# not compilers (see toolkit.nix), and the SBCL in the profile is usable without
# Quicklisp — you get ANSI CL and lose `(ql:quickload)`.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  # The seeded, writable copy. Quicklisp's own home directory is this, and every
  # path Quicklisp computes is relative to it.
  quicklispHome = "${config.home.homeDirectory}/.local/share/quicklisp";
in

{
  # The seed. Copied once into the writable directory above, and only when
  # setup.lisp is not already there — so this is idempotent and costs nothing
  # on every rebuild after the first.
  #
  # `cp -rT` rather than a symlink: a symlink would put every one of the writes
  # above back into the read-only store, which is the failure this file is
  # about. `chmod -R u+w` because the store's read-only bits are preserved by
  # `cp` and Quicklisp has to rewrite its .cdb files.
  # Form and ordering are the same as `createOrgSetup` in ./emacs/default.nix:
  # a bare shell string through `dag.entryAfter "writeBoundary"`, because that
  # is what this home-manager's `home.activation` takes (an attrset with a
  # `data` field is not the type — see the note at the end of this file).
  home.activation.seedQuicklisp = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    mkdir -p "${quicklispHome}"

    if [ ! -e "${quicklispHome}/setup.lisp" ]; then
      cp -rT --no-preserve=mode,ownership "${pkgs.quicklisp}/share/quicklisp" "${quicklispHome}"
      chmod -R u+w "${quicklispHome}"
    fi

    true
  '';

  # `~/.sbclrc`. SBCL reads this before the REPL, so `(ql:quickload …)` works at
  # the first prompt with nothing typed first. The `probe-file` guard means the
  # activation above has already run; without it, loading setup.lisp out of a
  # half-seeded directory fails on a first login after a rebuild that only
  # added the directory.
  home.file.".sbclrc".text = ''
    ;;; .sbclrc --- generated by modules/home/lisp.nix -*- lexical-binding: t; -*-
    ;; Do not edit: home-manager owns this file. Put your own Lisp in
    ;; ~/.config/common-lisp/user.lisp, which is loaded after this.

    (when (probe-file "${quicklispHome}/setup.lisp")
      (load "${quicklispHome}/setup.lisp"))
  '';

  # `~/.config/common-lisp/user.lisp` is where your own code belongs, and SBCL
  # loads it after .sbclrc — so QL is already available in it. Created so there
  # is somewhere obvious to put the first thing you write.
  home.file.".config/common-lisp/user.lisp".text = ''
    ;;;; user.lisp --- your Lisp goes here. -*- lexical-binding: t; -*-
    ;;;; Loaded after ~/.sbclrc, so (ql:quickload "...") works in this file.
  '';
}
